@startuml changePassword

actor User as "User"
boundary "Change Password Page" as View #lightblue
participant ":authRoute" as Route #lightblue
control "authMiddleware" as Auth #orange
control "authController" as Controller #lightblue
participant ":authService" as Service #lightblue
entity "userModel" as Model #lightblue
database "MongoDB" as MongoDB #yellow

group Change Password
User -> View: 1.Enter oldPassword, newPassword
activate View
activate User

View -> View: 2.Validate input
activate View
deactivate View

opt Weak new password
    View --> User: 2.1.Display "Password must least 6 characters"
end

View -> Route: 3.POST /api/v1/auth/changePassword
activate Route
Route -> Auth: 4. authenticateUser(req) & authorizeRole()
activate Auth
ref over Auth : 5. 3.0 Verify Token & Check Role

opt Authentication/Authorization Failed
    Auth --> Route: 5.1. Return 401/403 Error
    Route --> View: 5.2. Show error
    View --> User: 5.3. Display error message
end
Auth --> Route: 6. User authenticated & authorized
deactivate Auth

Route -> Controller: 7.changePassword(req, res)
activate Controller

Controller -> Service: 8.changePassword\n(userId, oldPassword, newPassword)
activate Service

Service -> Model: 9.findUserById(userId)
activate Model

Model -> MongoDB: 10.ExecuteQuery()
activate MongoDB
MongoDB --> Model: 11.Return result

Model --> Service: 12.Return result


alt Incorrect old password
    Service --> Controller: 12.1.Return fail 
    Controller --> Route: 12.1.1.Return fail
    Route --> View: 12.1.2.Show error
    View --> User: 12.1.3.Display "Old password is incorrect"

else New password same as old password
    Service --> Controller: 12.2.Return fail
    Controller --> Route: 12.2.1.Return fail
    Route --> View: 12.2.2.Show error
    View --> User: 12.2.3.Display "New password cannot same old password"

else Correct old password and strong new password
    Service -> Model: 12.3.updatePassword\n(userId, newHashedPassword)

    Model -> MongoDB: 12.3.1.ExecuteQuery()
    MongoDB --> Model: 12.3.2.Return result
    deactivate MongoDB

    Model --> Service: 12.3.3.Return result
    deactivate Model

    Service --> Controller: 12.3.4.Return success
    deactivate Service

    Controller --> Route: 12.3.5.Return success
    deactivate Controller

    Route --> View: 12.3.6.Show success
    deactivate Route

    View --> User: 12.3.7.Display "Changed successfully"
    deactivate View
    deactivate User
end
end 
@enduml
