@startuml changePassword

actor User as "User"
boundary "ChangePassword Page" as View #lightblue
participant ":authRoute" as Route #lightblue
control "authController" as Controller #lightblue
participant ":authService" as Service #lightblue
entity "userModel" as Model #lightblue
database "MongoDB" as MongoDB #yellow

group Change Password
User -> View: 1.Enter oldPassword, newPassword
activate View
activate User

View -> View: 2.Validate input
activate View
deactivate View

opt Weak new password
    View --> User: 2.1.Display "Password must least 6 characters"
end

View -> Route: 3.POST /api/v1/auth/changePassword
activate Route

Route -> Controller: 4.changePassword(req, res)
activate Controller

Controller -> Service: 5.changePassword\n(userId, oldPassword, newPassword)
activate Service

Service -> Model: 6.findUserById(userId)
activate Model

Model -> MongoDB: 7.ExecuteQuery()
activate MongoDB
MongoDB --> Model: 8.Return result

Model --> Service: 9.Return result


alt Incorrect old password
    Service --> Controller: 9.1.Return fail 
    Controller --> Route: 9.1.1.Return fail
    Route --> View: 9.1.2.Show error
    View --> User: 9.1.3.Display "Old password is incorrect"

else New password same as old password
    Service --> Controller: 9.2.Return fail
    Controller --> Route: 9.2.1.Return fail
    Route --> View: 9.2.2.Show error
    View --> User: 9.2.3.Display "New password cannot same old password"

else Correct old password and strong new password
    Service -> Model: 10.updatePassword\n(userId, newHashedPassword)

    Model -> MongoDB: 11.ExecuteQuery()
    MongoDB --> Model: 12.Return result
    deactivate MongoDB

    Model --> Service: 13.Return result
    deactivate Model

    Service --> Controller: 14.Return success
    deactivate Service

    Controller --> Route: 15.Return success
    deactivate Controller

    Route --> View: 16.Show success
    deactivate Route

    View --> User: 17.Display "Changed successfully"
    deactivate View
    deactivate User
end
end 
@enduml
