@startuml ForgotPassword

actor User as "User"
boundary "ForgotPassword Page" as View #lightblue
participant ":authRoute" as Route #lightblue
control "authController" as Controller #lightblue
participant ":authService" as Service #lightblue
entity "userModel" as Model #lightblue
database "MongoDB" as MongoDB #yellow
participant ":EmailService" as Mailer #pink

group Forgot Password
User -> View: 1.Click "Forgot Password" on login page
activate View
activate User
User -> View: 2.Enter email to reset password

View -> View: 3.Validate email input

alt Invalid email address
    View --> User: 3.1.Display "User not found. Please check again."
else Valid email
    View -> Route: 4.POST /api/v1/auth/forgotPassword
    activate Route

    Route -> Controller: 5.forgotPassword(req, res)
    activate Controller

    Controller -> Service: 6.forgotPassword(email)
    activate Service

    Service -> Model: 7.findUserByEmail(email) & generate OTP
    activate Model

    Model -> MongoDB: 8.ExecuteQuery()
    activate MongoDB
    MongoDB --> Model: 9.Return user

    Model --> Service: 10.Return user

    alt Email not registered
        Service --> Controller: 10.1.Return error "Email not found"
        Controller --> Route: 10.2.404 Not Found
        Route --> View: 10.3.Show "Email not found"
        View --> User: 10.4.Display error
    else Email found
        Service -> Mailer: 11.Send reset email with token/link
        activate Mailer
        Mailer --> Service: 12.Email sent
        deactivate Mailer

        Service --> Controller: 13.Return success
        Controller --> Route: 14.Return success

        Route --> View: 15.Show success

        View --> User: 16.Display "Please check your email"

        User -> View: 17.Enter OTP & new password
View -> View: 18.Validate OTP & password

alt OTP expired or maximum attempts exceeded
    View --> User: 18.1.Display "OTP invalid, expired or too many attempts. Please request a new OTP."
else OTP valid
    View -> Route: 19.POST /api/v1/auth/resetPassword

    Route -> Controller: 20.resetPassword(req, res)

    Controller -> Service: 21.resetPassword(email, newPassword)

    alt Password not valid (too short, same as old)
        Controller --> Route: 21.1.Return error
        Route --> View: 21.2.Show "Password does not meet requirements"
        View --> User: 21.3.Display error
    else Password valid
        Service -> Model: 22.FindAndUpdate(email, newPassword)
        Model -> MongoDB: 23.Update user password
        MongoDB --> Model: 24.Password updated
        deactivate MongoDB
        Model --> Service: 25.Return success
        deactivate Model

        Service --> Controller: 26.Return success
        deactivate Service
        Controller --> Route: 27.Return success
        deactivate Controller
        Route --> View: 28.Success
        deactivate Route
        View --> User: 29."Password reset successfully"
        deactivate View
        deactivate User
    end
end
end
end

@enduml
