@startuml Logout

actor User as "User"
boundary "Home Page" as View #lightblue
participant ":authRoute" as Routes_FE #lightblue
control "authController" as Controller #lightblue
participant ":authService" as Service #lightblue

group Logout
User -> View: 1.Click logout button
activate User
activate View

View -> Routes_FE: 2.POST /api/v1/auth/logout
activate Routes_FE

Routes_FE -> Controller: 3.logout(req, res)
activate Controller


    Controller -> Service: 4.logout(token)
    activate Service

    Service --> Controller: 5. Return success
    deactivate Service

alt Token valid / not blocked
    Controller --> Routes_FE: 5.1. Return success

    Routes_FE --> View: 5.1.1. Response success and clear token

    View --> User: 5.1.2. Redirect to login page

else Token missing or account blocked
    Controller --> Routes_FE: 5.2. Ignore token cancellation\nand redirect to login
    deactivate Controller


    Routes_FE --> View: 5.2.1.Response (redirect)
    deactivate Routes_FE
    View --> User: 5.2.2.Redirect to login page
    deactivate View
    deactivate User
end
end
@enduml