@startuml Logout

actor User as "User"
boundary "Home Page" as View #lightblue
participant ":authRoute" as Routes_FE #lightblue
control "authController" as Controller #lightblue
participant ":authService" as Service #lightblue

group Logout
User -> View: 1.Click logout button
activate User
activate View

View -> Routes_FE: 2.POST /api/v1/auth/logout
activate Routes_FE

Routes_FE -> Controller: 3.logout(req, res)
activate Controller

alt Token valid / not blocked
    Controller -> Service: 4.logout(token)
    activate Service

    Service -> Service: 5.Remove token\n(Memory)
    Service --> Controller: 6. Return success
    deactivate Service

    Controller --> Routes_FE: 6.1. Return success

    Routes_FE --> View: 6.1.1. Response success

    View -> View: 6.1.2. Remove token from localStorage
    View -> View: 6.1.3. Clear user state
    View --> User: 6.1.4. Redirect to login page

else Token missing or account blocked
    Controller --> Routes_FE: 6.2. Ignore token cancellation\nand redirect to login
    deactivate Controller


    Routes_FE --> View: 6.2.1.Response (redirect)
    deactivate Routes_FE
    View --> User: 6.2.2.Redirect to login page
    deactivate View
    deactivate User
end
end
@enduml