@startuml EditProfile

actor User
boundary "Profile Page" as View #lightblue
participant ":authRoute" as Route #lightblue
control "authController" as Controller #lightblue
participant ":authService" as Service #lightblue
entity "userModel" as Model #lightblue
database "MongoDB" as MongoDB #yellow

group Edit Profile
User -> View: 1. Click "Edit"
activate View
activate User
User -> View: 2. Edit avatar, gender, height, weight, dob.


View -> Route: 3. POST /api/v1/auth/profile
activate Route

Route -> Controller: 4. editProfile(req, res)
activate Controller

alt Update Failed
    Controller -> Service: 5. editProfile(userId, profileData)
    activate Service

    Service -> Model: 6. updateUserById(userId, profileData)
    activate Model

    Model -> MongoDB: 7. ExecuteQuery()
    activate MongoDB
    MongoDB --> Model: 8. Return result
    deactivate MongoDB

    Model --> Service: 9. Return update result
    deactivate Model


    Service --> Controller: 9.1. Return error
    Controller --> Route: 9.1.1 Internal Server Error
    Route --> View: 9.1.2. Show "Update failed"
    View --> User: 9.1.3. Display error message
else Update Success
    Service --> Controller: 9.2. Return updated user
    deactivate Service
    Controller --> Route: 9.2.1. Return success
    deactivate Controller
    Route --> View: 9.2.2. Show success
    deactivate Route
    View --> User: 9.2.3. Display "Updated successfully"
    deactivate View
    deactivate User
end
end
@enduml
