@startuml Signup

actor User as "User"
boundary "Register Page" as View #lightblue
participant ":authRoute" as Routes_FE #lightblue
control "authController" as Controller #lightblue
participant ":authService" as Service #lightblue
entity "userModel" as Model #lightblue
database "MongoDB" as MongoDB #yellow

group Register
User -> View: 1.Enter signup information\n(username, email, password)

activate View
activate User

View -> View: 2.Validate input
activate View
deactivate View

opt Invalid data
    View --> User: 2.1.Display validation errors
end
    View -> Routes_FE: 3.POST /api/v1/auth/signup
    activate Routes_FE

    Routes_FE -> Controller: 4.signup(req, res)
    activate Controller

    Controller -> Service: 5.createUser(userData)
    activate Service

    Service -> Model: 6.findOne({email},{username})
    activate Model

    Model -> MongoDB: 7.Check email/username exist 
    activate MongoDB
    MongoDB --> Model: 8.Return result
    deactivate MongoDB

    Model --> Service: 9.Return result
    deactivate Model

    alt Email/Username not exist
        Service -> Model: 9.1.create(userData)
        activate Model

        Model -> MongoDB: 9.2.Execute insert
        activate MongoDB
        MongoDB --> Model: 9.3.Return result
        deactivate MongoDB

        Model --> Service: 9.4.Return new user
        deactivate Model

        Service --> Controller: 9.5.Return success {token}

        Controller --> Routes_FE: 9.6.Created\n{message, user, token}

        Routes_FE --> View: 9.7.Success response and save token

        View --> User: 9.8.Redirect to login

    else Email/Username exist
        Service --> Controller: 9.a.Fail {message: "Email/Username exists"}
        deactivate Service

        Controller --> Routes_FE: 9.b.Return Fail {message}
        deactivate Controller

        Routes_FE --> View: 9.c.Error response
        deactivate Routes_FE

        View --> User: 9.d.Show error "Email/Username exists"
        deactivate View
        deactivate User
    end

end
@enduml
