import 'dotenv/config'

// GET VARIABLE FROM ENVIRONMENT
export const env = {
  AUTHOR: process.env.AUTHOR,
  MONGODB_URI: process.env.MONGODB_URI,
  DATABASE_NAME: process.env.DATABASE_NAME,
  DISPLAY_HOST: process.env.DISPLAY_HOST,
  HOST: process.env.HOST,
  PORT: process.env.PORT,

  UPSTASH_REDIS_URL: process.env.UPSTASH_REDIS_URL,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,

  YOUR_GOOGLE_CLIENT_ID: process.env.YOUR_GOOGLE_CLIENT_ID,
  YOUR_GOOGLE_CLIENT_SECRET: process.env.YOUR_GOOGLE_CLIENT_SECRET,
  GMAIL_USER: process.env.GMAIL_USER,
  GMAIL_PASS: process.env.GMAIL_PASS,
  DISPLAY_HOST: process.env.DISPLAY_HOST
}
