import 'dotenv/config'

// GET VARIABLE FROM ENVIRONMENT
export const env = {
  MONGODB_URI: process.env.MONGODB_URI,
  DATABASE_NAME: process.env.DATABASE_NAME,
  HOST: process.env.HOST,
  PORT: process.env.PORT,
  AUTHOR: process.env.AUTHOR,
  UPSTASH_REDIS_URL: process.env.UPSTASH_REDIS_URL,
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET,
  YOUR_GOOGLE_CLIENT_ID: process.env.YOUR_GOOGLE_CLIENT_ID,
  YOUR_GOOGLE_CLIENT_SECRET: process.env.YOUR_GOOGLE_CLIENT_SECRET,
  GMAIL_USER: process.env.GMAIL_USER,
  GMAIL_PASSWORD: process.env.GMAIL_PASSWORD
}
