@startuml UpdateRating

actor User as "Customer"
boundary "Dish Detail Page" as View #lightblue
participant ":ratingRoute" as Route #lightblue
control "authMiddleware" as Auth #Orange
control "ratingController" as Controller #lightblue
participant ":ratingService" as Service #lightblue
entity "ratingModel" as Model #lightblue
database "MongoDB" as MongoDB #yellow

group Update Rating
    User -> View: 1. Click frame rating and review
    activate User
    activate View

    View --> View: 2. Show rating and review modal
    activate View
    deactivate View

    opt User cancels
        View --> User: 2.1. Cancel rating (modal closed)
    end

    User -> View: 3. Enter review and select number star
    View -> View: 4. Validate input
    activate View
    deactivate View
    opt Invalid Input
        View --> User: 4.1. Display "Review is required shortest 10 characters."
    end

    View -> Route: 4. PATCH /api/v1/rating { ratingId, star, description }
    activate Route
    Route -> Auth: 5. authenticateUser(req) & authorizeRole()
    activate Auth
    ref over Auth : 6. Verify Token & Check Role

    opt Authentication/Authorization Failed
        Auth --> Route: 6.1. Return 401/403 Error
        Route --> View: 6.2. Show error
        View --> User: 6.3. Display error message
    end
    Auth --> Route: 7. User authenticated & authorized
    deactivate Auth

    Route -> Controller: 8. updateRating(req, res)
    activate Controller

    Controller -> Service: 9. updateRating(ratingData)
    activate Service

    Service -> Model: 10. updateRating(ratingData)
    activate Model

    Model -> MongoDB: 11. Update existing rating
    activate MongoDB
    MongoDB --> Model: 12. Return created rating
    deactivate MongoDB

    Model --> Service: 13. Return result
    deactivate Model

    Service --> Controller: 14. Return updated rating
    deactivate Service

    Controller --> Route: 15. 200 OK + rating
    deactivate Controller

    Route --> View: 16. Render updated rating
    deactivate Route

    View --> User: 17. Display updated rating
    deactivate View
    deactivate User
end 


@enduml